---
# This is a role for setting up the client.

- name: Set default shell and sudo
  user:
    name: 'kypo'
    shell: '/bin/bash'
    group: 'sudo'
    append: yes

- name: Setting a welcome message for attacker on machine
  copy:
    src: welcome.txt
    dest: '/home/kypo/welcome.txt'
    owner: kypo
    mode: 0644

- name: Install packages
  apt:
    pkg:
     - nmap
     - hydra
     - medusa
    update_cache: yes

- name: Add passwords file to the home directory
  copy:
    src: passlist.txt
    dest: /home/kypo/passlist.txt
    owner: kypo
    mode: 0644

...
